In [ ]:
import pandas as pd

In [ ]:
df=pd.read_excel('/content/Data_Cleaning_Exercise_Salary_Survey.xlsx')
df['What country do you work in?']

0         United States
1        United Kingdom
2                    US
3                   USA
4                    US
              ...
28143     United States
28144         Thailand
28145           ENGLAND
28146               USA
28147             India
Name: What country do you work in?, Length: 28148, dtype: object

In [ ]:
df['What country do you work in?']

0         United States
1        United Kingdom
2                    US
3                   USA
4                    US
              ...
28143     United States
28144         Thailand
28145           ENGLAND
28146               USA
28147             India
Name: What country do you work in?, Length: 28148, dtype: object

**Renaming Columns**

In [ ]:
#renaming all columns names
df.columns=df.columns.str.title().str.strip()
df
df.rename(columns={'Timestamp':'Time'},inplace=True)
df
df.rename(columns={'How Old Are You?':'Age'},inplace=True)
df
df.rename(columns={'Job Title':'Job'},inplace=True)
df
df.rename(columns={'If Your Job Title Needs Additional Context, Please Clarify Here:':'Additional Job Title'},inplace=True)
df
df.rename(columns={'What Industry Do You Work In?':'Industry'},inplace=True)
df
df.rename(columns={"What Is Your Annual Salary? (You'Ll Indicate The Currency In A Later Question. If You Are Part-Time Or Hourly, Please Enter An Annualized Equivalent -- What You Would Earn If You Worked The Job 40 Hours A Week, 52 Weeks A Year.)":'Salary'},inplace=True)
df
df.rename(columns={'How Much Additional Monetary Compensation Do You Get, If Any (For Example, Bonuses Or Overtime In An Average Year)? Please Only Include Monetary Compensation Here, Not The Value Of Benefits.':'Additional Monetary Compensation'},inplace=True)
df
df.rename(columns={'Please Indicate The Currency':'Currency'},inplace=True)
df
df.rename(columns={'If "Other," Please Indicate The Currency Here:':'Other Currency'},inplace=True)
df
df.rename(columns={'If Your Income Needs Additional Context, Please Provide It Here:':'Additional Context Income'},inplace=True)
df
df.rename(columns={'How Many Years Of Professional Work Experience Do You Have Overall?':'Years Of Professional Work Experience Overall'},inplace=True)
df
df.rename(columns={'How Many Years Of Professional Work Experience Do You Have In Your Field?':'Years Of Professional Work Experience Field'},inplace=True)
df
df.rename(columns={'What Is Your Highest Level Of Education Completed?':'Level Education'},inplace=True)
df
df.rename(columns={'What Is Your Gender?':'Gender'},inplace=True)
df
df.rename(columns={'What Is Your Race? (Choose All That Apply.)':'Race'},inplace=True)
df
df.rename(columns={'Cleaning Task - Country':'Cleaning Country'},inplace=True)
df
df.rename(columns={'Cleaning Task - Salary':'Cleaning Salary'},inplace=True)
df
df.rename(columns={'Cleaning Task - Experience':'Cleaning Experience'},inplace=True)
df
df.rename(columns={'Cleaning Task - Currency':'Cleaning Currency'},inplace=True)
df
df.rename(columns={'Cleaning Task - Missing Compensation':'Cleaning Missing Compensation'},inplace=True)
df
df.rename(columns={'What Country Do You Work In?':'Country'},inplace=True)
df
df.rename(columns={"If You'Re In The U.S., What State Do You Work In?":'State'},inplace=True)
df
df.rename(columns={'What City Do You Work In?':'City'},inplace=True)
df

,Time,Age,Industry,Job,Additional Job Title,Salary,Additional Monetary Compensation,Currency,Other Currency,Additional Context Income,...,Years Of Professional Work Experience Overall,Years Of Professional Work Experience Field,Level Education,Gender,Race,Cleaning Country,Cleaning Salary,Cleaning Experience,Cleaning Currency,Cleaning Missing Compensation
0,2021-04-27 11:02:09.743,25-34,Education (Higher Education),Research and Instruction Librarian,NaN,55000,0.0,USD,NaN,NaN,...,5-7 years,5-7 years,Master's degree,Woman,White,NaN,NaN,NaN,NaN,NaN
1,2021-04-27 11:02:21.562,25-34,Computing or Tech,Change & Internal Communications Manager,NaN,54600,4000.0,GBP,NaN,NaN,...,8 - 10 years,5-7 years,College degree,Non-binary,White,NaN,NaN,NaN,NaN,NaN
2,2021-04-27 11:02:38.125,25-34,"Accounting, Banking & Finance",Marketing Specialist,NaN,34000,NaN,USD,NaN,NaN,...,2 - 4 years,2 - 4 years,College degree,Woman,White,Standardize to 'United States',NaN,NaN,NaN,Fill with 0 or mark as missing
3,2021-04-27 11:02:40.643,25-34,Nonprofits,Program Manager,NaN,62000,3000.0,USD,NaN,NaN,...,8 - 10 years,5-7 years,College degree,Woman,White,Standardize to 'United States',NaN,NaN,NaN,NaN
4,2021-04-27 11:02:41.793,25-34,"Accounting, Banking & Finance",Accounting Manager,NaN,60000,7000.0,USD,NaN,NaN,...,8 - 10 years,5-7 years,College degree,Woman,White,Standardize to 'United States',NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28143,2025-06-06 22:03:16.301,25-34,Business or Consulting,Business Analyst,NaN,86000,NaN,USD,NaN,NaN,...,8 - 10 years,8 - 10 years,Master's degree,Woman,Black or African American,NaN,NaN,NaN,NaN,Fill with 0 or mark as missing
28144,2025-06-08 10:38:49.256,25-34,Transport or Logistics,Admin and HR Officer,NaN,19200,10200.0,Other,Thai Baht,NaN,...,2 - 4 years,1 year or less,College degree,Woman,Asian or Asian American,NaN,NaN,NaN,NaN,NaN
28145,2025-06-11 03:34:38.889,25-34,Health care,Senior DAWN Administrator,NHS,25000,NaN,GBP,NaN,NaN,...,2 - 4 years,2 - 4 years,College degree,Man,Another option not listed here or prefer not t...,NaN,NaN,NaN,NaN,Fill with 0 or mark as missing
28146,2025-06-18 14:23:13.669,18-24,Business or Consulting,Consultant/ Salesperson,NaN,8000,NaN,USD,NaN,NaN,...,2 - 4 years,1 year or less,High School,Woman,White,Standardize to 'United States',NaN,NaN,NaN,Fill with 0 or mark as missing
28147,2025-07-03 08:47:05.672,25-34,Engineering or Manufacturing,Data Analyst,NaN,1000000,30000.0,USD,NaN,NaN,...,5-7 years,5-7 years,College degree,Man,Asian or Asian American,NaN,NaN,NaN,NaN,NaN

**Check Null & Duplicate**

In [ ]:
#Check Null & Duplicate
df['Additional Job Title'].isnull()
df['Industry'].isnull()
df['Cleaning Country'].isnull()
df['Additional Monetary Compensation'].isnull()
df['Currency'].isnull()
df['Gender'].isnull()
df['Time'].duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
28143    False
28144    False
28145    False
28146    False
28147    False
Name: Time, Length: 28148, dtype: bool

**Removing Null**

In [ ]:
#Remove Nulls and Duplicates
from numpy import mean
df['Additional Job Title'].fillna('Unknown',inplace=True)
df
df['Additional Monetary Compensation'].fillna(df['Additional Monetary Compensation'].mean(),inplace=True)
df
df['Salary'].fillna(df['Salary'].mean(),inplace=True)
df
df['Industry'].str.strip()
df
df['Industry'].str.title()
df
df['Job']=df['Job'].replace('Data Analysis','Data Analyst')
df
df['Other Currency'].fillna('Unknown',inplace=True)
df['Currency'].fillna('Unknown',inplace=True)
df
df['Additional Context Income'].fillna('0',inplace=True)
df
df['Years Of Professional Work Experience Field']=df['Years Of Professional Work Experience Field'].replace('1 year or less','0-1 years')
df
df['Job']=df['Job'].replace('Data Analysis','Data Analyst')
df
df['Years Of Professional Work Experience Overall']=df['Years Of Professional Work Experience Overall'].replace('1 year or less','0-1 years')
df
df['Level Education'].str.strip()
df
#drop'Cleaning Country','Cleaning Salary','Cleaning Experience','Cleaning Currency','Cleaning Missing Compensation'
df.drop(['Cleaning Country','Cleaning Salary','Cleaning Experience','Cleaning Currency','Cleaning Missing Compensation'],axis=1,inplace=True)
df

/tmp/ipykernel_2864/2051288124.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Additional Job Title'].fillna('Unknown',inplace=True)
/tmp/ipykernel_2864/2051288124.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Additional Monetary Compensation'].fillna(df['Additional Monetary Compensation'].mean(),inplace=True)
/tmp/ipykernel_2864/2051288124.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Salary'].fillna(df['Salary'].mean(),inplace=True)
/tmp/ipykernel_2864/2051288124.py:15: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Other Currency'].fillna('Unknown',inplace=True)
/tmp/ipykernel_2864/2051288124.py:16: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Currency'].fillna('Unknown',inplace=True)
/tmp/ipykernel_2864/2051288124.py:18: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Additional Context Income'].fillna('0',inplace=True)

,Time,Age,Industry,Job,Additional Job Title,Salary,Additional Monetary Compensation,Currency,Other Currency,Additional Context Income,Country,State,City,Years Of Professional Work Experience Overall,Years Of Professional Work Experience Field,Level Education,Gender,Race
0,2021-04-27 11:02:09.743,25-34,Education (Higher Education),Research and Instruction Librarian,Unknown,55000,0.000000,USD,Unknown,0,United States,Massachusetts,Boston,5-7 years,5-7 years,Master's degree,Woman,White
1,2021-04-27 11:02:21.562,25-34,Computing or Tech,Change & Internal Communications Manager,Unknown,54600,4000.000000,GBP,Unknown,0,United Kingdom,NaN,Cambridge,8 - 10 years,5-7 years,College degree,Non-binary,White
2,2021-04-27 11:02:38.125,25-34,"Accounting, Banking & Finance",Marketing Specialist,Unknown,34000,18234.491207,USD,Unknown,0,US,Tennessee,Chattanooga,2 - 4 years,2 - 4 years,College degree,Woman,White
3,2021-04-27 11:02:40.643,25-34,Nonprofits,Program Manager,Unknown,62000,3000.000000,USD,Unknown,0,USA,Wisconsin,Milwaukee,8 - 10 years,5-7 years,College degree,Woman,White
4,2021-04-27 11:02:41.793,25-34,"Accounting, Banking & Finance",Accounting Manager,Unknown,60000,7000.000000,USD,Unknown,0,US,South Carolina,Greenville,8 - 10 years,5-7 years,College degree,Woman,White
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28143,2025-06-06 22:03:16.301,25-34,Business or Consulting,Business Analyst,Unknown,86000,18234.491207,USD,Unknown,0,United States,North Carolina,Charlotte,8 - 10 years,8 - 10 years,Master's degree,Woman,Black or African American
28144,2025-06-08 10:38:49.256,25-34,Transport or Logistics,Admin and HR Officer,Unknown,19200,10200.000000,Other,Thai Baht,0,Thailand,NaN,Bangkok,2 - 4 years,0-1 years,College degree,Woman,Asian or Asian American
28145,2025-06-11 03:34:38.889,25-34,Health care,Senior DAWN Administrator,NHS,25000,18234.491207,GBP,Unknown,0,ENGLAND,NaN,READING,2 - 4 years,2 - 4 years,College degree,Man,Another option not listed here or prefer not t...
28146,2025-06-18 14:23:13.669,18-24,Business or Consulting,Consultant/ Salesperson,Unknown,8000,18234.491207,USD,Unknown,0,USA,Pennsylvania,Greensburg,2 - 4 years,0-1 years,High School,Woman,White
28147,2025-07-03 08:47:05.672,25-34,Engineering or Manufacturing,Data Analyst,Unknown,1000000,30000.000000,USD,Unknown,0,India,Colorado,Banglore,5-7 years,5-7 years,College degree,Man,Asian or Asian American

In [ ]:
df['Industry'].fillna('Not Provided',inplace=True)
df
df['Gender'].fillna('Not Provided',inplace=True)
df
df['Gender'].str.strip()
df
df['Gender'].str.title()

/tmp/ipykernel_2864/2237405474.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Industry'].fillna('Not Provided',inplace=True)
/tmp/ipykernel_2864/2237405474.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Gender'].fillna('Not Provided',inplace=True)

0             Woman
1        Non-Binary
2             Woman
3             Woman
4             Woman
            ...
28143         Woman
28144         Woman
28145           Man
28146         Woman
28147           Man
Name: Gender, Length: 28148, dtype: object

**Replace Duplicated Values in Country Column**

In [ ]:
#replace Values in Country and City
#country
df['Country']=df['Country'].replace('USA','United States')
df
df['Country']=df['Country'].replace('US','United States')
df
df['Country']=df['Country'].str.title()
df
df['Country']=df['Country'].replace('usa','United States')
df
df['Country']=df['Country'].replace('UK','United Kingdom')
df
df['Country']=df['Country'].replace('U.S.','United States')
df
df['Country']=df['Country'].replace('us','United States')
df
df['Country']=df['Country'].replace('us','United States')
df
df['Country']=df['Country'].replace('United States of America','United States')
df
df['Country']=df['Country'].replace('united states','United States')
df
df['Country']=df['Country'].replace('canada','Canada')
df
df['Country']=df['Country'].replace('U.S>','United States')
df
df['Country']=df['Country'].replace('ISA','United States')
df
df['Country']=df['Country'].replace('The Netherlands','Netherlands')
df
df['Country']=df['Country'].replace('U.S.A','United States')
df
df['Country']=df['Country'].replace('united states','United States')
df
df['Country']=df['Country'].replace('U.S.A.','United States')
df
df['Country']=df['Country'].replace('United State','United States')
df
df['Country']=df['Country'].replace('Us','United States')
df
df['Country']=df['Country'].replace('Česká republika','Czech Republic')
df
df['Country']=df['Country'].replace('United Stares','United States')
df
df['Country']=df['Country'].replace('dbfemf','Unknown')
df
df['Country']=df['Country'].replace('us','United States')
df
df['Country']=df['Country'].replace('ss','Unknown')
df
df['Country']=df['Country'].replace('ibdia','India')
df
df['Country']=df['Country'].replace('Scotland,UK','United Kingdom')
df
df['Country']=df['Country'].replace('United States of American','United States')
df
df['Country']=df['Country'].replace('Company in Germany. I work from Pakistan.','Unknown')
df
df['Country']=df['Country'].replace('Scotland','United Kingdom')
df
df['Country']=df['Country'].replace('England','United Kingdom')
df
df['Country']=df['Country'].str.strip()
df['Country']=df['Country'].fillna('Unknown')
df['Country'].value_counts()

Country
United States      21413
Canada              1681
Usa                 1123
United Kingdom       812
Uk                   692
                   ...
Tanzania               1
Česká Republika        1
Italia                 1
Hong Kongkong          1
Egypt                  1
Name: count, Length: 262, dtype: int64

In [ ]:
df['Country'].unique()

array(['United States', 'United Kingdom', 'Canada', 'Usa', 'Uk',
       'Scotland', 'Netherlands', 'Australia', 'Spain', 'Finland',
       'United States Of America', 'France', 'Germany', 'Ireland',
       'India', 'U.S.', 'Isa', 'Argentina', 'Great Britain', 'Us',
       'Denmark', 'America', 'England', 'Switzerland', 'Bermuda',
       'The United States', 'United State Of America', 'Malaysia',
       'Mexico', 'United Stated', 'South Africa', 'Belgium',
       'Northern Ireland', 'Sweden', 'Hong Kong', 'Kuwait', 'Norway',
       'Sri Lanka', 'Contracts', 'Usa-- Virgin Islands', 'United Statws',
       'England/Uk', 'U.S',
       "We Don'T Get Raises, We Get Quarterly Bonuses, But They Periodically Asses Income In The Area You Work, So I Got A Raise Because A 3Rd Party Assessment Showed I Was Paid Too Little For The Area We Were Located",
       'Unites States', 'U.S.A.', 'England, Uk.', 'Greece', 'Japan',
       'U. S.', 'Britain', 'United Sates', 'Austria', 'Brazil',
       'Canada, Ottawa, Ontario', 'Global', 'United States Of American',
       'Uniited States', 'United Kingdom (England)',
       'Worldwide (Based In Us But Short Term Trips Aroudn The World)',
       'Canadw', 'Hungary', 'Luxembourg', 'United Sates Of America',
       'United States (I Work From Home And My Clients Are All Over The Us/Canada/Pr',
       'Colombia', 'Unted States', 'United Statesp', 'United Stattes',
       'United Statea', 'United Kingdom.', 'New Zealand',
       'Trinidad And Tobago', 'United Statees', 'Cayman Islands', 'Can',
       'I Am Located In Canada But I Work For A Company In The Us',
       'Uniyed States', 'Uniyes States', 'United States Of Americas',
       'U.A.', 'Czech Republic', 'Czechia', 'Latvia', 'Puerto Rico',
       'Us Of A', 'Rwanda', 'United Arab Emirates', 'Bangladesh', 'U.K.',
       'Romania', 'U.Sa', 'United Kindom', 'United Status',
       'Currently Finance', 'Serbia', 'Philippines', 'Russia', 'Poland',
       'Uxz', 'England, Uk', 'Turkey', 'Canda', 'Canada And Usa',
       'Catalonia', '$2,175.84/Year Is Deducted For Benefits',
       'Italy (South)', 'Jersey, Channel Islands', 'China', 'Virginia',
       'Afghanistan', 'Israel', 'Uss', 'Uniteed States',
       'New Zealand Aotearoa', 'Hartford', 'Japan, Us Gov Position',
       'Csnada', 'Mainland China', 'I.S.', 'Uk (Northern Ireland)',
       'Uk For U.S. Company', 'Nz', 'Taiwan', 'Canad', 'Unite States',
       'The Us', 'The Netherlands', 'Cambodia', 'Vietnam', 'Remote',
       'Singapore', 'South Korea', 'Thailand', 'Lithuania', 'Eritrea',
       'Indonesia',
       'For The United States Government, But Posted Overseas', 'Is',
       'United Kingdomk', 'Italy', 'Cuba', 'Slovenia', 'Australi',
       "Cote D'Ivoire", 'From Romania, But For An Us Based Company',
       'Somalia', 'Wales (United Kingdom)', 'England, Gb', 'Unitedstates',
       'Danmark', 'U.K. (Northern England)', 'U.K', 'Nl', 'Nederland',
       'Slovakia', 'Portugal', 'England, United Kingdom', 'Sierra Leone',
       'Englang', 'United Statew', 'Uae',
       'Bonus Based On Meeting Yearly Goals Set W/ My Supervisor',
       'International', 'The Bahamas', 'Wales',
       "I Earn Commission On Sales. If I Meet Quota, I'M Guaranteed Another 16K Min. Last Year I Earned An Additional 27K. It'S Not Uncommon For People In My Space To Earn 100K+ After Commission.",
       'Costa Rica', 'United Statues', 'Untied States',
       'Usa (Company Is Based In A Us Territory, I Work Remote)', 'Chile',
       'Uk (England)', 'Uk, Remote', 'Scotland, Uk', 'Usab',
       'Unitied States', 'Qatar', 'United Sttes', 'Remote (Philippines)',
       'Unites Kingdom', 'Nigeria', 'Panamá',
       'Austria, But I Work Remotely For A Dutch/British Company',
       "I Work For An Us Based Company But I'M From Argentina.",
       'I Was Brought In On This Salary To Help With The Ehr And Very Quickly Was Promoted To Current Position But Compensation Was Not Altered.',
       'Uniter Statez', 'U. S', 'Congo', 'Uruguay', 'Pakistan', 'Brasil',
       'Usa Tomorrow', 'United Stateds',
       'N/A (Remote From Wherever I Want)',
       'Us Govt Employee Overseas, Country Withheld', 'Uganda', 'Malta',
       'Saudi Arabia', 'Bulgaria', 'Estonia', 'Morocco', 'Africa',
       'Ecuador', 'Zimbabwe', 'Ghana', 'San Francisco', 'Usat', '🇺🇸',
       'Luxemburg', 'Unitef Stated', 'Ua', 'Wales, Uk', 'United Stares',
       'Croatia', 'Usaa', 'Ukraine', 'United States- Puerto Rico',
       'From New Zealand But On Projects Across Apac', 'Y', 'United Y',
       'Wales (Uk)', 'Isle Of Man', 'Northern Ireland, United Kingdom',
       'Europe', 'California',
       'Uk, But For Globally Fully Remote Company', 'Australian',
       'México', 'Jamaica', 'Usd', "Usa, But For Foreign Gov'T", 'Kenya',
       'Jordan', 'United Statss', 'Argentina But My Org Is In Thailand',
       'I Work For A Uae-Based Organization, Though I Am Personally In The Us.',
       'United  States', 'Aotearoa New Zealand', 'Na', 'Policy', 'Cyprus',
       'Hong Konh', 'United States Is America', 'Liechtenstein',
       'Company In Germany. I Work From Pakistan.', 'Canadá', 'U.S.A',
       'Bosnia And Herzegovina', 'London', 'Ss', 'Dbfemf', 'Ibdia',
       'Loutreland', 'Ff', 'Myanmar', 'Burma', 'Tanzania',
       'Česká Republika', 'Italia', 'Hong Kongkong', 'Egypt'],
      dtype=object)

In [ ]:
# @title
#Country update
df['Country'] = df['Country'].replace({
    'United  States': 'United States',
    'Usa': 'United States',
    'Great Britain': 'United Kingdom',
    'Aotearoa New Zealand': 'New Zealand',
    'Na': 'Unknown',
    'Policy': 'Unknown'
})
df['Country']
df['Country'].value_counts()
df['Country'].value_counts().sort_index()
df['Country'] = df['Country'].replace({
    'America': 'United States',
    '🇺🇸': 'United States',
    'Italia': 'Italy',
    'Burma': 'Myanmar',
    'Hong Kongkong': 'Hong Kong',
    '$2,175.84/Year Is Deducted For Benefits': 'Unknown',
    'Africa': 'Unknown',
    'Y': 'Unknown'
})
df['Country'].value_counts().head(20)
df['Country'] = df['Country'].replace({
    'Uk': 'United Kingdom',
    'United States Of America': 'United States',
    'England': 'United Kingdom',
    'Us': 'United States'
})
df['Country'].value_counts().head(20)
df['Country'] = df['Country'].replace({
    'U.S': 'United States',
    'U.S.': 'United States'
})
df['Country'].value_counts().head(20)
df['Country'] = df['Country'].replace(
    'Unites States',
    'United States'
)
df['Country']=df['Country'].fillna('Unknown')
df['Country'].value_counts()
df['Country'].value_counts().head(20)

Country
United States     23137
Canada             1681
United Kingdom     1541
Australia           390
Germany             197
Ireland             125
New Zealand         124
Netherlands          87
France               68
Spain                50
Sweden               41
Switzerland          38
Belgium              35
Japan                29
India                24
Denmark              23
Singapore            20
South Africa         19
Austria              18
Finland              16
Name: count, dtype: int64

**Replace Duplicated Values in City Column**

In [ ]:
#replace Values in Cities
df['City'].value_counts()
df['City']=df['City'].replace({'Banglore':'Bangalore'
,'Milano':'Milan',
'Tifton, Valdosta, Jacksonville':'Multiple Cities','Jhonston':'Johnston',
'G':'Unknown','Home Plus Travel To Customers. Near Chicago':'Unknown',
'Berkeley, Ca':'Berkeley',
'Boise-But Remote. Company Located In Boston':'Unknown',
'Ff':'Unknown','Newyork':'New York',
'Alexandria, La':'Alexandria','Confidential':'Unknown',
'Boh':'Unknown','Stgo':'Santiago',
"A Small Village In Okinawa Prefecture (Sorry, It'S Too Identifying)":'Unknown',
'Mclean Though I Travel Some':'Unknown','Dublin Ireland':'Dublin',
'Irvine, Ca':'Irvine','Ottawa Area':'Ottawa',
'I Don’T Live In A City; I Am Very Rural':'Unknown',
'Declined':'Unknown','Bay Of Plenty':'Unknown',
'Seattle (Remote)':'Seattle','Chicago / Ft Remote':'Chicago',
'New York City (Remote)':'New York','Beaverton, Or (Portland Suburb)':'Beaverton',
'Marlton, Nj':'Marlton','“Large” Canadian Prairie City.':'Unknown',
'Annandale Va':'Annandale','Nyc Suburb':'Unknown'})
df['City']=df['City'].str.title()
df['City']
df['City']=df['City'].str.strip()
df['City']
df['City'].value_counts()
df['City']

0             Boston
1          Cambridge
2        Chattanooga
3          Milwaukee
4         Greenville
            ...
28143      Charlotte
28144        Bangkok
28145        Reading
28146     Greensburg
28147      Bangalore
Name: City, Length: 28148, dtype: object

In [ ]:
#State Replace Values
df['State']=df['State'].replace({'NaN':'Unknown',
'Alabama, South Carolina':'Unknown',
'Colorado, Delaware, New Jersey, West Virginia, Wyoming':'Unknown',
'Utah, Wisconsin':'Unknown',
'Delaware, Louisiana':'Unknown','Florida, Georgia':'Unknown',
'California, Illinois, Massachusetts, North Carolina, South Carolina, Virginia':'Unknown','Alabama, California':'Unknown',
'Michigan, Texas, Washington':'Unknown','Alabama, Oregon':'Unknown',
'Alabama, Alaska, Arizona':'Unknown',
'California, District of Columbia, Illinois, Iowa, Maryland, Minnesota':'Unknown',
'Oregon, Washington':'Unknown','New York, Virginia':'Unknown',
'Mississippi, Missouri':'Unknown','California, Maryland':'Unknown',
'Pennsylvania, Rhode Island':'Unknown','New York, Oregon, Vermont':'Unknown',
'Iowa, Nebraska':'Unknown','California, New York':'Unknown',
'Arizona, New York':'Unknown','Pennsylvania, Rhode Island':'Unknown',
'New York, Oregon, Vermont':'Unknown','Iowa, Nebraska':'Unknown',
'California, New York':'Unknown','Arizona, New York':'Unknown',
'California, Maryland':'Unknown','Oregon, Washington':'Unknown','New York, Virginia':'Unknown',
'Florida, New Hampshire, Wisconsin':'Unknown'})
df['State'] = df['State'].fillna('Unknown')
#Use If Statment
df['State'] = df['State'].apply(
    lambda x: 'Unknown' if ',' in str(x) else x
)
df['State'].value_counts()

State
Unknown                 5161
California              2614
New York                2179
Massachusetts           1523
Texas                   1270
Illinois                1213
Washington              1185
District of Columbia     983
Pennsylvania             945
Virginia                 786
Minnesota                723
Ohio                     656
Colorado                 634
Oregon                   626
North Carolina           602
Maryland                 564
Michigan                 553
Georgia                  552
Florida                  522
Wisconsin                469
New Jersey               399
Missouri                 345
Indiana                  329
Arizona                  302
Tennessee                286
Connecticut              239
Utah                     209
Kentucky                 191
Iowa                     179
Kansas                   153
South Carolina           148
Louisiana                129
Maine                    126
Alabama                  122
New Hampshire            118
Oklahoma                 113
Nebraska                 110
New Mexico                98
Idaho                     97
Nevada                    94
Rhode Island              77
Arkansas                  72
Vermont                   68
Alaska                    66
Montana                   64
Mississippi               51
Delaware                  47
West Virginia             42
North Dakota              35
Hawaii                    30
South Dakota              25
Wyoming                   24
Name: count, dtype: int64

**Convert salary and compensation fields**

In [ ]:
#Convert salary and compensation fields to numeric format: Remove any non-numeric characters and convert to numbers.
df['Currency'].fillna('Unknown')
df['Salary'].head(20)
df['Additional Monetary Compensation'].head(20)
#Unify currency column: If currency is marked as 'Other' and no specification is provided, (other)
df['Currency']=df['Currency'].replace('Other','Unknown')
df['Currency']
df.duplicated().sum()
df['Gender'].fillna('Unknown')

0             Woman
1        Non-binary
2             Woman
3             Woman
4             Woman
            ...
28143         Woman
28144         Woman
28145           Man
28146         Woman
28147           Man
Name: Gender, Length: 28148, dtype: object

In [ ]:
#Age Replace
df['Age']=df['Age'].replace('40000','Not Provided')
df['Age'].value_counts()
#Industry Replace
df['Industry']=df['Industry'].replace({'5000.0':'Not Provided','PhD':'Not Provided',
'Librarian':'Public Library',"I'M Currently A Student And Don'T Have A Job":'Student',
'Library--Public':'Public Library','Ks)"':'Not Provided',
'0.0':'Not Provided','250.0':'Not Provided','21 - 30 years':'Not Provided'})
df['Industry']=df['Industry'].str.title().str.strip()
df['Industry']=df['Industry'].fillna('Not Provided')
df['Industry'].value_counts()
#Job replace
df['Job']=df['Job'].replace('9-12 grade teacher','Teacher')
df['Job']=df['Job'].str.title().str.strip()
df['Job']
df['Job'].value_counts()
#Salary Replace
df['Salary']=df['Salary'].fillna(df['Salary'].mean())
df['Salary'].value_counts()
df['Salary'].isna().sum()
df['Additional Monetary Compensation']=df['Additional Monetary Compensation'].fillna(df['Additional Monetary Compensation'].mean())
df['Additional Monetary Compensation'].value_counts()

Additional Monetary Compensation
0.000000        7963
18234.491207    7336
5000.000000     1114
10000.000000     962
2000.000000      776
                ...
35553.000000       1
22.000000          1
10320.000000       1
9075.000000        1
71845.000000       1
Name: count, Length: 850, dtype: int64

In [ ]:
#Replace Other Currency
df['Other Currency']=df['Other Currency'].replace({'-':'Unknown','0':'Unknown','1':'Unknown','11 - 20 years':'Unknown',
'47000':'Unknown','5':'Unknown','55000':'Unknown','76303.34':'Unknown'})
df['Other Currency'].value_counts()
#Replace Country
df['Country']=df['Country'].replace({'5-7 years':'Unknown','Ff':'Unknown'})
df['Country'].value_counts()
#Level Education
df['Level Education']=df['Level Education'].fillna('Unknown')
df['Level Education'].value_counts()
#Race Replace
df['Race']=df['Race'].fillna('Unknown')
df['Race'].value_counts()
df['Race'].isna().sum()
#time replace data type
df['Time']=pd.to_datetime(df['Time'])

In [ ]:
df.to_csv('New Salary_2021 After Cleaning.CSV',index=False)

In [ ]:
data = pd.read_csv('/content/New Salary_2021 After Cleaning.CSV')
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28148 entries, 0 to 28147
Data columns (total 18 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   Time                                           28148 non-null  object
 1   Age                                            28148 non-null  object
 2   Industry                                       28148 non-null  object
 3   Job                                            28146 non-null  object
 4   Additional Job Title                           28148 non-null  object
 5   Salary                                         28148 non-null  int64
 6   Additional Monetary Compensation               28148 non-null  float64
 7   Currency                                       28148 non-null  object
 8   Other Currency                                 28148 non-null  object
 9   Additional Context Income                      28148 non-null  object
 10  Country                                        28148 non-null  object
 11  State                                          28148 non-null  object
 12  City                                           28043 non-null  object
 13  Years Of Professional Work Experience Overall  28148 non-null  object
 14  Years Of Professional Work Experience Field    28148 non-null  object
 15  Level Education                                28148 non-null  object
 16  Gender                                         28148 non-null  object
 17  Race                                           28148 non-null  object
dtypes: float64(1), int64(1), object(16)
memory usage: 3.9+ MB

In [ ]:
#minmax normalization (way1)
max_Salary=df['Salary'].max()
min_Salary=df['Salary'].min()
min_max_normalization=(df['Salary']-min_Salary)/(max_Salary-min_Salary)
min_max_normalization.head()

0    0.000009
1    0.000009
2    0.000006
3    0.000010
4    0.000010
Name: Salary, dtype: float64

In [ ]:
#minmax normalization (way2)
from sklearn.preprocessing import MinMaxScaler
df['min_max_normalization']=MinMaxScaler().fit_transform(df[['Salary']])
df['min_max_normalization'].head()

0    0.000009
1    0.000009
2    0.000006
3    0.000010
4    0.000010
Name: min_max_normalization, dtype: float64

In [ ]:
#z_score (way1)
Salary_mean=df['Salary'].mean()
Salary_Std=df['Salary'].std()
Z_Score_Normalization=(df['Salary']-Salary_mean)/Salary_Std
Z_Score_Normalization.head()

0   -0.008531
1   -0.008542
2   -0.009112
3   -0.008338
4   -0.008393
Name: Salary, dtype: float64

In [ ]:
#z_Score (way2)
from sklearn.preprocessing import StandardScaler
df['Z_Score_normalization']=StandardScaler().fit_transform(df[['Salary']])
df['Z_Score_normalization'].head()

0   -0.008531
1   -0.008542
2   -0.009112
3   -0.008338
4   -0.008393
Name: Z_Score_normalization, dtype: float64

In [ ]:
#robust normalization (way1)
Q1=df['Salary'].quantile(0.25)
Q3=df['Salary'].quantile(0.75)
IQR=Q3-Q1
Salary_medin=df['Salary'].median()
robust_normalization=(df['Salary']-Salary_medin)/IQR
robust_normalization.head()

0   -0.360198
1   -0.367402
2   -0.738406
3   -0.234129
4   -0.270149
Name: Salary, dtype: float64

In [ ]:
#Robust Normalization (way2)
from sklearn.preprocessing import RobustScaler
df['Robust Normalization']=RobustScaler().fit_transform(df[['Salary']])
df['Robust Normalization'].head()

0   -0.360198
1   -0.367402
2   -0.738406
3   -0.234129
4   -0.270149
Name: Robust Normalization, dtype: float64

In [ ]:
#decimal Normalization
Max_Value=abs(df['Salary'].max())
length=len(str(Max_Value))
df['decimal_Normalization']=df['Salary']/(10**length)
df['decimal_Normalization'].head()

0    0.000005
1    0.000005
2    0.000003
3    0.000006
4    0.000006
Name: decimal_Normalization, dtype: float64

In [ ]:
df

,Time,Age,Industry,Job,Additional Job Title,Salary,Additional Monetary Compensation,Currency,Other Currency,Additional Context Income,...,City,Years Of Professional Work Experience Overall,Years Of Professional Work Experience Field,Level Education,Gender,Race,min_max_normalization,Z_Score_normalization,Robust Normalization,decimal_Normalization
0,2021-04-27 11:02:09.743,25-34,Education (Higher Education),Research And Instruction Librarian,Unknown,55000,0.000000,USD,Unknown,0,...,Boston,5-7 years,5-7 years,Master's degree,Woman,White,0.000009,-0.008531,-0.360198,5.500000e-06
1,2021-04-27 11:02:21.562,25-34,Computing Or Tech,Change & Internal Communications Manager,Unknown,54600,4000.000000,GBP,Unknown,0,...,Cambridge,8 - 10 years,5-7 years,College degree,Non-binary,White,0.000009,-0.008542,-0.367402,5.460000e-06
2,2021-04-27 11:02:38.125,25-34,"Accounting, Banking & Finance",Marketing Specialist,Unknown,34000,18234.491207,USD,Unknown,0,...,Chattanooga,2 - 4 years,2 - 4 years,College degree,Woman,White,0.000006,-0.009112,-0.738406,3.400000e-06
3,2021-04-27 11:02:40.643,25-34,Nonprofits,Program Manager,Unknown,62000,3000.000000,USD,Unknown,0,...,Milwaukee,8 - 10 years,5-7 years,College degree,Woman,White,0.000010,-0.008338,-0.234129,6.200000e-06
4,2021-04-27 11:02:41.793,25-34,"Accounting, Banking & Finance",Accounting Manager,Unknown,60000,7000.000000,USD,Unknown,0,...,Greenville,8 - 10 years,5-7 years,College degree,Woman,White,0.000010,-0.008393,-0.270149,6.000000e-06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28143,2025-06-06 22:03:16.301,25-34,Business Or Consulting,Business Analyst,Unknown,86000,18234.491207,USD,Unknown,0,...,Charlotte,8 - 10 years,8 - 10 years,Master's degree,Woman,Black or African American,0.000014,-0.007674,0.198109,8.600000e-06
28144,2025-06-08 10:38:49.256,25-34,Transport Or Logistics,Admin And Hr Officer,Unknown,19200,10200.000000,Unknown,Thai Baht,0,...,Bangkok,2 - 4 years,0-1 years,College degree,Woman,Asian or Asian American,0.000003,-0.009521,-1.004953,1.920000e-06
28145,2025-06-11 03:34:38.889,25-34,Health Care,Senior Dawn Administrator,NHS,25000,18234.491207,GBP,Unknown,0,...,Reading,2 - 4 years,2 - 4 years,College degree,Man,Another option not listed here or prefer not t...,0.000004,-0.009361,-0.900495,2.500000e-06
28146,2025-06-18 14:23:13.669,18-24,Business Or Consulting,Consultant/ Salesperson,Unknown,8000,18234.491207,USD,Unknown,0,...,Greensburg,2 - 4 years,0-1 years,High School,Woman,White,0.000001,-0.009831,-1.206664,8.000000e-07
28147,2025-07-03 08:47:05.672,25-34,Engineering Or Manufacturing,Data Analyst,Unknown,1000000,30000.000000,USD,Unknown,0,...,Bangalore,5-7 years,5-7 years,College degree,Man,Asian or Asian American,0.000167,0.017597,16.659163,1.000000e-04

In [ ]:
df.to_csv("Salary Survey_2021 cleaning.CSV",index=False)
df

,Time,Age,Industry,Job,Additional Job Title,Salary,Additional Monetary Compensation,Currency,Other Currency,Additional Context Income,...,City,Years Of Professional Work Experience Overall,Years Of Professional Work Experience Field,Level Education,Gender,Race,min_max_normalization,Z_Score_normalization,Robust Normalization,decimal_Normalization
0,2021-04-27 11:02:09.743,25-34,Education (Higher Education),Research And Instruction Librarian,Unknown,55000,0.000000,USD,Unknown,0,...,Boston,5-7 years,5-7 years,Master's degree,Woman,White,0.000009,-0.008531,-0.360198,5.500000e-06
1,2021-04-27 11:02:21.562,25-34,Computing Or Tech,Change & Internal Communications Manager,Unknown,54600,4000.000000,GBP,Unknown,0,...,Cambridge,8 - 10 years,5-7 years,College degree,Non-binary,White,0.000009,-0.008542,-0.367402,5.460000e-06
2,2021-04-27 11:02:38.125,25-34,"Accounting, Banking & Finance",Marketing Specialist,Unknown,34000,18234.491207,USD,Unknown,0,...,Chattanooga,2 - 4 years,2 - 4 years,College degree,Woman,White,0.000006,-0.009112,-0.738406,3.400000e-06
3,2021-04-27 11:02:40.643,25-34,Nonprofits,Program Manager,Unknown,62000,3000.000000,USD,Unknown,0,...,Milwaukee,8 - 10 years,5-7 years,College degree,Woman,White,0.000010,-0.008338,-0.234129,6.200000e-06
4,2021-04-27 11:02:41.793,25-34,"Accounting, Banking & Finance",Accounting Manager,Unknown,60000,7000.000000,USD,Unknown,0,...,Greenville,8 - 10 years,5-7 years,College degree,Woman,White,0.000010,-0.008393,-0.270149,6.000000e-06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28143,2025-06-06 22:03:16.301,25-34,Business Or Consulting,Business Analyst,Unknown,86000,18234.491207,USD,Unknown,0,...,Charlotte,8 - 10 years,8 - 10 years,Master's degree,Woman,Black or African American,0.000014,-0.007674,0.198109,8.600000e-06
28144,2025-06-08 10:38:49.256,25-34,Transport Or Logistics,Admin And Hr Officer,Unknown,19200,10200.000000,Unknown,Thai Baht,0,...,Bangkok,2 - 4 years,0-1 years,College degree,Woman,Asian or Asian American,0.000003,-0.009521,-1.004953,1.920000e-06
28145,2025-06-11 03:34:38.889,25-34,Health Care,Senior Dawn Administrator,NHS,25000,18234.491207,GBP,Unknown,0,...,Reading,2 - 4 years,2 - 4 years,College degree,Man,Another option not listed here or prefer not t...,0.000004,-0.009361,-0.900495,2.500000e-06
28146,2025-06-18 14:23:13.669,18-24,Business Or Consulting,Consultant/ Salesperson,Unknown,8000,18234.491207,USD,Unknown,0,...,Greensburg,2 - 4 years,0-1 years,High School,Woman,White,0.000001,-0.009831,-1.206664,8.000000e-07
28147,2025-07-03 08:47:05.672,25-34,Engineering Or Manufacturing,Data Analyst,Unknown,1000000,30000.000000,USD,Unknown,0,...,Bangalore,5-7 years,5-7 years,College degree,Man,Asian or Asian American,0.000167,0.017597,16.659163,1.000000e-04